### ISSUE TITLE
Identifier rect_size not declared in current scope

### ISSUE THREAD

**Issue by 0Pranav** [Calinou/godot-overscan-demo#1]
In the file overscan.gd

I am testing the project out to get an idea for a possible godot engine implementation. Am I missing something obvious here?

**Comment by Calinou** [comment]
The Control `rect_size` property was recently renamed to `size` in the `master` branch, so this demo needs to be updated.

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/godot-overscan-demo/commit/8f4dd195e32e15bd961bd150d6da43fb876198b2.
